### ISSUE TITLE
Unable to run the .jar

### ISSUE THREAD

**Issue by EvanHeavenn** [ThatOneCalculator/Among-Us-Dumpy-Gif-Maker#10]
whenever i try and run the jar file it says that a " jni error has occurred " and then that a " java exception has occurred " 
![Screenshot_2](https://user-images.githubusercontent.com/84932364/119879470-a770eb80-bf01-11eb-93d1-58160ca9949d.png)
![Screenshot_3](https://user-images.githubusercontent.com/84932364/119879499-af309000-bf01-11eb-8ea7-6a604442fa29.png)
I've checked and can confirm that i am running the latest release of java

**Comment by ThatOneCalculator** [comment]
Is this using the latest release (which comes in a zip folder)?

**Comment by karl-police** [comment]
I get the same issue btw.

**Comment by EvanHeavenn** [comment]
> Is this using the latest release (which comes in a zip folder)?
yes

**Comment by ThatOneCalculator** [comment]
Could you open CMD and type `java --version`, and paste the output?

**Comment by EvanHeavenn** [comment]
> Could you open CMD and type `java --version`, and paste the output?

it said that it didn't recognize the command

**Comment by ThatOneCalculator** [comment]
That means you didn't install Java properly.

**Comment by ThatOneCalculator** [comment]
https://download.oracle.com/otn-pub/java/jdk/16.0.1+9/7147401fd7354114ac51ef3e1328291f/jdk-16.0.1_windows-x64_bin.exe

**Comment by EvanHeavenn** [comment]
here 
`java version "1.8.0_291"
Java(TM) SE Runtime Environment (build 1.8.0_291-b10)
Java HotSpot(TM) 64-Bit Server VM (build 25.291-b10, mixed mode)`
i just used one "-"

**Comment by ThatOneCalculator** [comment]
You need to be on version 15 or later, you're on 8.

**Comment by ThatOneCalculator** [comment]
https://download.oracle.com/otn-pub/java/jdk/16.0.1+9/7147401fd7354114ac51ef3e1328291f/jdk-16.0.1_windows-x64_bin.exe <- Use that

**Comment by EvanHeavenn** [comment]
well it works now, but do you know why the recommended version of java on the website is version 8?

**Comment by ThatOneCalculator** [comment]
> well it works now, but do you know why the recommended version of java on the website is version 8?

The README says to use 15/16. This app uses new Java features, 8 is for LTS (Long Term Support).

**Comment by ThatOneCalculator** [comment]
@karl-police @EvanHeavenn I'd advise you both to update to the latest version, it has a few bug fixes and is just better in general

**Comment by karl-police** [comment]
> @karl-police @EvanHeavenn I'd advise you both to update to the latest version, it has a few bug fixes and is just better in general

I build the .java myself I'm still doing the UI thing
