### ISSUE TITLE
Discord Bot seems to show images from other servers

### ISSUE THREAD

**Issue by deesnuhtz** [ThatOneCalculator/Among-Us-Dumpy-Gif-Maker#15]
The Discord bot seems to be showing incorrect images, which may be from other discord servers.
![E2fiSxOWUAIc2ov](https://user-images.githubusercontent.com/84988750/120023656-ba43f880-bfb3-11eb-966c-7817a6992e1e.png)

**Comment by ThatOneCalculator** [comment]
Could you please send the message ID of this message?
![image](https://user-images.githubusercontent.com/44733677/120023745-1c483200-bfa3-11eb-8a07-dd9a3361c84a.png)

**Comment by deesnuhtz** [comment]
sure! the message ID is 847892000874954762

**Comment by ThatOneCalculator** [comment]
Ok! I've done some investigation, and the image is downloaded fine, but the output got swapped for whatever reason.
`attach_847892000874954762.png`
![attach_847892000874954762](https://user-images.githubusercontent.com/44733677/120024431-0dae4a80-bfa4-11eb-8377-46cb764cdec3.png)

`dumpy847892000874954762.gif`
![dumpy847892000874954762](https://user-images.githubusercontent.com/44733677/120024466-1868df80-bfa4-11eb-802f-646293f134e3.gif)

I'm going to look into this further and see what I can do :)

**Comment by ThatOneCalculator** [comment]
I think I found the issue @deesnuhtz !

I'm going to change line 169 in sus.java from
```java
runCmd("convert -delay 1x20 ./F_* -loop 0 " + output);
```
to
```
runCmd("convert -delay 1x20 ./F_*" + extraoutput + ".png -loop 0 " + output);
```

which should help track the intermediary files

**Comment by ThatOneCalculator** [comment]
I tested it by running 2 at once, it should be fine now. I would love if you could take down or correct the Tweets that highlight this issue, now that it's resolved.

If you enjoy this project, a star would be wonderful!

If you don't have any further questions, I'll close the issue

**Comment by ThatOneCalculator** [comment]
Closing, assuming everything is fine

**Comment by deesnuhtz** [comment]
thank you!
