### ISSUE TITLE
Error when attempting to install from AUR on Manjaro

### ISSUE THREAD

**Issue by VoxelDraqon** [ThatOneCalculator/Among-Us-Dumpy-Gif-Maker#16]
```
:: Proceed with installation? [Y/n] 
(1/1) checking keys in keyring                     [######################] 100%
(1/1) checking package integrity                   [######################] 100%
(1/1) loading package files                        [######################] 100%
(1/1) checking for file conflicts                  [######################] 100%
(1/1) checking available disk space                [######################] 100%
:: Processing package changes...
(1/1) installing among-us-dumpy-gif-maker          [######################] 100%
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
Error: Could not find or load main class .usr.lib.jvm.java-15-openjdk.bin.java
Caused by: java.lang.ClassNotFoundException: /usr/lib/jvm/java-15-openjdk/bin/java
```
`/usr/lib/jvm/java-15-openjdk/bin/java` _does_ exist

**Comment by ThatOneCalculator** [comment]
> ```
Error: Could not find or load main class .usr.lib.jvm.java-15-openjdk.bin.java
Caused by: java.lang.ClassNotFoundException: /usr/lib/jvm/java-15-openjdk/bin/java1
```

Was this part of the `among-us-dumpy-gif-maker` command or part of the AUR package installing?

**Comment by VoxelDraqon** [comment]
This is part of the installation

**Comment by ThatOneCalculator** [comment]
Did you run `yay -S among-us-dumpy-gif-maker && among-us-dumpy-gif-maker` like it says in the repo, or JUST `yay -S among-us-dumpy-gif-maker`? This really doesn't look like part of the PKGBUILD

**Comment by VoxelDraqon** [comment]
ah you're right, I did run the full thing

**Comment by ThatOneCalculator** [comment]
Can you run `cat /usr/bin/among-us-dumpy-gif-maker`?

**Comment by VoxelDraqon** [comment]
```
#!/bin/sh

/usr/lib/jvm/java-1*-openjdk/bin/java -jar /usr/lib/Among-Us-Dumpy-Gif-Maker-1.6.0-all.jar
```

**Comment by ThatOneCalculator** [comment]
Can you run `/usr/lib/jvm/java-1*-openjdk/bin/java -jar /usr/lib/Among-Us-Dumpy-Gif-Maker-1.6.0-all.jar` in your shell prompt?

**Comment by VoxelDraqon** [comment]
```
Error: Could not find or load main class .usr.lib.jvm.java-15-openjdk.bin.java
Caused by: java.lang.ClassNotFoundException: /usr/lib/jvm/java-15-openjdk/bin/java
```
but `/usr/lib/jvm/java-15-openjdk/bin/java` definitely exists

**Comment by ThatOneCalculator** [comment]
can you run `/usr/lib/jvm/java-15-openjdk/bin/java -version`?

**Comment by VoxelDraqon** [comment]
```
openjdk version "15.0.2" 2021-01-19
OpenJDK Runtime Environment (build 15.0.2+7)
OpenJDK 64-Bit Server VM (build 15.0.2+7, mixed mode)
```

**Comment by ThatOneCalculator** [comment]
Can you run `archlinux-java status`?

**Comment by VoxelDraqon** [comment]
```
Available Java environments:
  java-11-openjdk
  java-15-openjdk
  java-16-openjdk (default)
  java-8-openjdk
```

**Comment by ThatOneCalculator** [comment]
Can you run `/usr/lib/jvm/java-15-openjdk/bin/java -jar /usr/lib/Among-Us-Dumpy-Gif-Maker-1.6.0-all.jar`?

**Comment by VoxelDraqon** [comment]
that one works

**Comment by ThatOneCalculator** [comment]
Ok! I'm a bit busy, I'll update the AUR package in a bit :)

**Comment by ThatOneCalculator** [comment]
@VoxelDraqon can you run `yay -Syu` and then run the program?

**Comment by VoxelDraqon** [comment]
it's still throwing the same error

**Comment by ThatOneCalculator** [comment]
Could you run `cat /usr/bin/among-us-dumpy-gif-maker` again?

**Comment by VoxelDraqon** [comment]
```
#!/bin/sh

/usr/lib/jvm/java-1*-openjdk/bin/java -jar /usr/lib/Among-Us-Dumpy-Gif-Maker-1.6.0-all.jar
```

**Comment by ThatOneCalculator** [comment]
That means you didn't cleanbuild when you updated, which is always bad practice. 

`yay -Rnscd among-us-dumpy-gif-maker && yay -S among-us-dumpy-gif-maker`

**Comment by VoxelDraqon** [comment]
ok that is a good thing to know because I heard somewhere else that that didn't matter so I was confused about that for a while. It does work now

**Comment by ThatOneCalculator** [comment]
Whoever told you that is an absolute dunce, CleanBuild takes out the old files and puts in the new ones while non-cleanbuild only clones the latest source repo (IF applicable, it's not here) and updates the version number. PLEASE ALWAYS CLEANBUILD! It will save you so many headaches.

Also, word of advice. Manjaro is a really flawed and insecure distro. If you want something Arch based that's not Arch, I'd recommend [EndeavourOS](https://endeavouros.com).

Anyway, hope you have a good day! If you like this project, feel free to leave a star, it helps out a bunch and it's free <3
