### ISSUE TITLE
discord bot wont work

### ISSUE THREAD

**Issue by StardustBytez** [ThatOneCalculator/Among-Us-Dumpy-Gif-Maker#17]
i was trying to use the discord bot and i gave it the permissions embed links and attach files
it wouldn't work and even tried giving it administrator but still it didnt work 
help would be appreciated, thank you!

**Comment by ThatOneCalculator** [comment]
I think I actually just fixed the issue, could you try the command again?

**Comment by StardustBytez** [comment]
its working now, thanks!

**Comment by ThatOneCalculator** [comment]
No problem! Sorry for that problem, it was a problem with upgrading the discord_buttons library.
