### ISSUE TITLE
Discord bot wacky colors

### ISSUE THREAD

**Issue by AlfredoMeister** [ThatOneCalculator/Among-Us-Dumpy-Gif-Maker#18]
when i run an image through the discord bot, the colors are completely off from the original image.

**Comment by ThatOneCalculator** [comment]
Hi! This is not a bug, the program uses a limited color pallette. It works best with sprites and flags. If you're doing a larger image with a larger resolution, you can try `!!dumpy resolution dither`.

**Comment by AlfredoMeister** [comment]
its a really simple red and white image but it is coming out as brown and purple.
![yeeyahyooyah](https://user-images.githubusercontent.com/85077457/120116446-324a2400-c156-11eb-8673-f4e48ef607a0.PNG)
![naughty dumpy bad colors](https://user-images.githubusercontent.com/85077457/120116454-37a76e80-c156-11eb-855d-b7bd43b3d03f.PNG)

**Comment by AlfredoMeister** [comment]
ive seen it do flags almost identical very accurately, but its not working at all for me

**Comment by ThatOneCalculator** [comment]
> its a really simple red and white image but it is coming out as brown and purple.
> ![yeeyahyooyah](https://user-images.githubusercontent.com/85077457/120116446-324a2400-c156-11eb-8673-f4e48ef607a0.PNG)
> ![naughty dumpy bad colors](https://user-images.githubusercontent.com/85077457/120116454-37a76e80-c156-11eb-855d-b7bd43b3d03f.PNG)
> 
> 

This has to do with the dark reds. It tends to categorize darker reds as brown, I'd reccomend lightening it just a little bit. I didn't write the original image generation code, that was Pixer, although I may work to make it better in the future

**Comment by AlfredoMeister** [comment]
thx. also the "!!dumpy 35" isnt working for me. but whatever
