### ISSUE TITLE
AUR's package bin script is pointed towards outdated java version

### ISSUE THREAD

**Issue by HurricanePootis** [ThatOneCalculator/Among-Us-Dumpy-Gif-Maker#21]
The package `jre-openjdk`, which used to have the java binary at `/usr/lib/jvm/java-15-openjdk/bin/java`, is now updated to JRE16, making the java binary located at `/usr/lib/lvm/java-16-openjdk/bin/java`.

Arch linux already system links the user's preferred version of java to `/usr/bin/java`, and it is unnecessary to manually point to a specific version.

**Comment by ThatOneCalculator** [comment]
Ok! I will fix that :)

**Comment by ThatOneCalculator** [comment]
@HurricanePootis done, ty
