### ISSUE TITLE
Why discord bot is down

### ISSUE THREAD

**Issue by APTEM591** [ThatOneCalculator/Among-Us-Dumpy-Gif-Maker#24]
Why bot is currently offline?
![IMG_20210628_214819](https://user-images.githubusercontent.com/71151134/123688379-95fd6500-d85a-11eb-9c02-378f3cf17d64.jpg)

**Comment by ThatOneCalculator** [comment]
Sorry, I'm trying to get it back up

**Comment by ThatOneCalculator** [comment]
Also please don't open issues for downtime
