### ISSUE TITLE
Can I use it on a Java app?

### ISSUE THREAD

**Issue by leapofazzam123** [ThatOneCalculator/Among-Us-Dumpy-Gif-Maker#25]
Is it really possible to do it? I want to make it an Android app so people don't need to use the Discord bot to make Among Us Dumpy GIF

**Comment by ThatOneCalculator** [comment]
The JAR file uses ImageMagick which doesn't work on mobile devices. Furthermore, we ask that you don't redistribute this program on other platforms.
