### ISSUE TITLE
can't read input file error?

### ISSUE THREAD

**Issue by CMolero** [ThatOneCalculator/Among-Us-Dumpy-Gif-Maker#31]
I keep getting this error when I try to run the jar, even if I run it as admin, tbh I tried google the error and didn't find anything in particular that might be causing it

![image](https://user-images.githubusercontent.com/5658513/125176114-53675100-e1a7-11eb-93ff-3c3696802420.png)

**Comment by ThatOneCalculator** [comment]
It's because you don't have ImageMagick static installed. Please read through the instructions thoroughly.

**Comment by CMolero** [comment]
> 
> 
> It's because you don't have ImageMagick static installed. Please read through the instructions thoroughly.

I'm sorry, but I, in fact, have imagemackick installed
![image](https://user-images.githubusercontent.com/5658513/125176296-c32a0b80-e1a8-11eb-9678-e84627f0c447.png)
and I can even use the imagemacking commands in the CLI
![image](https://user-images.githubusercontent.com/5658513/125176334-f1a7e680-e1a8-11eb-8081-1c9833d4b3f3.png)

**Comment by ThatOneCalculator** [comment]
You really can't read, can you? ImageMagick STATIC, not just regular ImageMagick. Link is in the README. Closing this issue now because you refuse to read.
