### ISSUE TITLE
You really can't read, can you? ImageMagick STATIC, not just regular ImageMagick. Link is in the README. Locking this issue now because you refuse to read.

### ISSUE THREAD

**Issue by CMolero** [ThatOneCalculator/Among-Us-Dumpy-Gif-Maker#32]
You really can't read, can you? ImageMagick STATIC, not just regular ImageMagick. Link is in the README. Locking this issue now because you refuse to read.

_Originally posted by @ThatOneCalculator in https://github.com/ThatOneCalculator/Among-Us-Dumpy-Gif-Maker/issues/31#issuecomment-877704180_

first of all, stop being so angry

second of all, I'm downloading the static one, the one linked in the github throws a 404, if you want me to download something specific then you need to refresh that link

![image](https://user-images.githubusercontent.com/5658513/125176507-60397400-e1aa-11eb-8f15-a6b19d463b1b.png)
 that's the one i have installed 

this is what you get if you click the link in the github
![image](https://user-images.githubusercontent.com/5658513/125176516-75ae9e00-e1aa-11eb-9c6a-adbc7d5426d3.png)

**Comment by ThatOneCalculator** [comment]
I'll look into the broken link, but yea don't double-issue.
