### ISSUE TITLE
Incorrect link in readme.md

### ISSUE THREAD

**Issue by JohnSmith777779** [ThatOneCalculator/Among-Us-Dumpy-Gif-Maker#36]
The [readme](https://www.oracle.com/java/technologies/javase-jdk16-downloads.html) says

> [All downloads](https://www.oracle.com/java/technologies/javase-jdk16-downloads.html)

but you're [only](https://github.com/ThatOneCalculator/Among-Us-Dumpy-Gif-Maker/issues/35#issuecomment-882232383) supposed to use the link below it

> Also works with [OpenJDK](https://adoptopenjdk.net/releases.html?variant=openjdk16&jvmVariant=hotspot)

> It says clearly on the repo to download Java 16. https://adoptopenjdk.net/releases.html?variant=openjdk16&jvmVariant=hotspot

Please remove the incorrect oracle.com link.

**Comment by ThatOneCalculator** [comment]
Stop opening issues. Both JDK 16 and OpenJDK 16 work with this program, you just don't like reading.
