### ISSUE TITLE
[Running on windows] "Invalid parameter - 1x20"

### ISSUE THREAD

**Issue by rcoppy** [ThatOneCalculator/Among-Us-Dumpy-Gif-Maker#43]
Hi there! Trying to use this tool on windows. 

Sometimes I can get an intermediate frame exported ("F_0.png") but looks like there might be a permissions issue with file access? So subsequent frames can't be smushed into a gif. 

Terminal readout: 

```
arcop@DESKTOP-AH3SOJ0 MINGW64 ~/Downloads
$ java -jar Among-Us-Dumpy-Gif-Maker-3.1.3-all.jar
C:\Users\arcop\Pictures\render.PNG
5
4
3
0
2
1
Converting....
Invalid Parameter - 1x20
Exception in thread "main" javax.imageio.IIOException: Can't read input file!
        at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1308)
        at dev.t1c.dumpy.sus.main(sus.java:254)
```

fyi am running in an elevated shell with admin privileges. 

Thanks! 🙂

**Comment by ThatOneCalculator** [comment]
Read the instructions. You haven't installed imagemagick correctly.

**Comment by rcoppy** [comment]
Hmm... care to elaborate? Your docs list dependencies but not config instructions. Looking at another closed issue it could be that my imagemagick version is too new; I would suggest making the versioning requirement for Windows explicit in your readme, because it's not clear.

**Comment by ThatOneCalculator** [comment]
It is explicit in the readme, it says 6.9.x for windows only (windows sucks balls)

**Comment by ThatOneCalculator** [comment]
When the impostor is sus!![Screenshot_20210924-095215.jpg](https://user-images.githubusercontent.com/44733677/134712376-0faacefd-12ac-4801-be4c-0e063a248260.jpg)
