### ISSUE TITLE
Add Character Limit in Text Command 

### ISSUE THREAD

**Issue by SpiderMath** [ThatOneCalculator/Among-Us-Dumpy-Gif-Maker#44]
The `text` command of the dumpy bot is bugged.
(Referring to the screenshot below)
![image](https://user-images.githubusercontent.com/71999854/134959077-94db6da9-ee09-4f72-a428-822d95ff8491.png)

Now, you might be thinking, it sent the complete text but in a smaller image, but nope 
![image](https://user-images.githubusercontent.com/71999854/134959257-ed58a30a-6268-43f0-a67a-93eeb8c562d2.png)

It cuts off at the `B` of the `Bot`
So please add a limit to the number of characters the user can provide (I think the limit should be 80 at max, but I could be wrong)

**Comment by SpiderMath** [comment]
Don't get offended on my text though :sweat_smile:

**Comment by ThatOneCalculator** [comment]
I think that this isn't that much of a major issue, thank you for finding the limit but I don't think that anyone would need to be warned if they need more than 80 amogus characters. Thank you for your findings, though!
