### ISSUE TITLE
the bot not sending image

### ISSUE THREAD

**Issue by ploplop101** [ThatOneCalculator/Among-Us-Dumpy-Gif-Maker#46]
when using the command !!dumpy and !!furry the bot types The !!background command has been updated! Run !!background delete to remove your current background, run !!background color for a solid color, !!background #AAAAAA for a custom color background, !!background flag for pride flags (gay, lesbian, trans, etc) and run !!background and attach an image for a custom image as a background. then says typing for 3-5 seconds and then does nothing

**Comment by ThatOneCalculator** [comment]
Chances are you attached the image wrong. It has to be sent as an attachment and can only be a png or jpg

**Comment by ploplop101** [comment]
I dont believe that this is the issues due to it being sent as an attachment and being a png
