### ISSUE TITLE
Spam issue/Off-topic

### ISSUE THREAD

**Issue by slingring** [ThatOneCalculator/Among-Us-Dumpy-Gif-Maker#51]
You know me, I asked you about your boyfriend and you banned me.
Drench lemon juice over your wounds. Don’t forget salt and ice.

**Comment by ThatOneCalculator** [comment]
Again, no clue who you are. Please private message me on Revolt, Discord or Misskey if you want to talk to me, using an issue tracker isn't the best mode of communication.
