### ISSUE TITLE
What is your discord?

### ISSUE THREAD

**Issue by slingring** [ThatOneCalculator/Among-Us-Dumpy-Gif-Maker#53]
You mentioned it, and I can’t contact you if you have me blocked and don’t provide said handle.
I don’t use the other two why are you bitching, I saw your petty attempt at email spam.

**Comment by slingring** [comment]
![1662BC0D-F493-4F26-A4B2-BE532E912A2A](https://user-images.githubusercontent.com/67127010/172461380-e885c52d-cf8e-4bb2-9959-4199e9d22e93.jpeg)
Please sob harder for me asking for your handles

**Comment by ThatOneCalculator** [comment]
My... petty attempt at email spam? You're the one ON MY ISSUE TRACKER and I have to clean up after your spam. 

I don't like using Discord anymore, but it's ThatOneCalculator#0001

**Comment by ThatOneCalculator** [comment]
Cc @slingring as I had to edit the message to show my tag properly
