### ISSUE TITLE
[Bug] Can't read color image -> JAR packaging issue

### ISSUE THREAD

**Issue by CrookedBeaker** [ThatOneCalculator/Among-Us-Dumpy-Gif-Maker#9]
After extracting the program and trying it on a solid black png, I noticed the individual frames are generated in the folder, but no gif. I tried running it through command line, and what resulted is in the screenshot below.

![image](https://user-images.githubusercontent.com/77556655/119866204-8ea90b80-beea-11eb-9ca8-65888ee9f312.png)

I'm using the latest version of AdoptOpenJDK.
Thank you for your time.

**Comment by ThatOneCalculator** [comment]
Sorry about that! I'm going to rebuild the JAR for fixes with Windows

**Comment by ThatOneCalculator** [comment]
https://github.com/ThatOneCalculator/Among-Us-Dumpy-Gif-Maker/releases/download/v1.2/Among-Us-Dumpy-Gif-Maker.jar

Please download this version, and let me know if it works :)

**Comment by CrookedBeaker** [comment]
Thanks, I'll check it out! It's all good.

**Comment by ThatOneCalculator** [comment]
For sure! Could you please let me know when you test it, so I can close the issue?

**Comment by CrookedBeaker** [comment]
I tried it again, but when I extracted the program, the jar file was missing within the folder I was extracting to. I then tried running it through the unextracted jar, put in the same file, and came up with a different issue altogether in the screenshot below.
![image](https://user-images.githubusercontent.com/77556655/119873224-50afe580-bef2-11eb-8f3e-4bfb528b4eff.png)
I apologize for this, I'm not terribly familiar with using java programs.

**Comment by ThatOneCalculator** [comment]
I'm now having the same issue too, give me a bit and I'll try and fix it. For now, either use the Discord bot OR use the git clone instructions (run from source)

**Comment by ThatOneCalculator** [comment]
@CrookedBeaker it had to do with the way Java was compiling the JAR, try this (unzip the file and run the JAR inside the folder)

https://github.com/ThatOneCalculator/Among-Us-Dumpy-Gif-Maker/releases/download/v1.3/AmongUsGifMaker.zip

**Comment by CrookedBeaker** [comment]
Will do, thanks!

**Comment by CrookedBeaker** [comment]
At last, it works!
Thank you for taking the time to fix this issue. Sorry to put you through all that trouble, haha
![dumpy](https://user-images.githubusercontent.com/77556655/119883304-64147e00-befd-11eb-87bb-0cc31f9ace75.gif)

**Comment by ThatOneCalculator** [comment]
It's no problem! I hope you have a good day :)
